
# Auto-generated by Interface Designer
#
# WARNING: Any manual changes made to this file will be lost when generating constraints.

# Efinity Interface Designer SDC
# Version: 2024.1.158
# Date: 2024-06-14 05:56

# Copyright (C) 2013 - 2024 Efinix Inc. All rights reserved.

# Device: Ti375N1156
# Project: efx_ethernet_10g_exp
# Timing Model: C4 (preliminary)
#               NOTE: The timing data is not final

# Oscillator Constraints
########################
#create_clock -period 12.5 [get_ports {osc_inst1_CLKOUT}]

# PLL Constraints
#################
create_clock -period 5.0000 DEBUG_CLK
create_clock -period 4.3478 Q1_APB_CLK
create_clock -period 4.3478 Q3_APB_CLK
create_clock -period 20.0000 INIT_CLK

# GPIO Constraints
####################

# JTAG Constraints
####################
create_clock -period 145 [get_ports {jtag_vio_TCK}]

set_output_delay -clock jtag_vio_TCK -max 2.452 [get_ports {jtag_vio_TDO}]
set_output_delay -clock jtag_vio_TCK -min 1.244 [get_ports {jtag_vio_TDO}]
set_input_delay -clock_fall -clock jtag_vio_TCK -max 0.917 [get_ports {jtag_vio_CAPTURE}]
set_input_delay -clock_fall -clock jtag_vio_TCK -min 0.469 [get_ports {jtag_vio_CAPTURE}]
set_input_delay -clock_fall -clock jtag_vio_TCK -max 1.488 [get_ports {jtag_vio_RESET}]
set_input_delay -clock_fall -clock jtag_vio_TCK -min 0.955 [get_ports {jtag_vio_RESET}]
set_input_delay -clock_fall -clock jtag_vio_TCK -max 0.878 [get_ports {jtag_vio_SEL}]
set_input_delay -clock_fall -clock jtag_vio_TCK -min 0.507 [get_ports {jtag_vio_SEL}]
set_input_delay -clock_fall -clock jtag_vio_TCK -max 0.853 [get_ports {jtag_vio_UPDATE}]
set_input_delay -clock_fall -clock jtag_vio_TCK -min 0.452 [get_ports {jtag_vio_UPDATE}]
set_input_delay -clock_fall -clock jtag_vio_TCK -max 0.985 [get_ports {jtag_vio_SHIFT}]
set_input_delay -clock_fall -clock jtag_vio_TCK -min 0.497 [get_ports {jtag_vio_SHIFT}]
#set_input_delay -clock_fall -clock jtag_vio_TCK -max 1.644 [get_ports {jtag_vio_DRCK}]
#set_input_delay -clock_fall -clock jtag_vio_TCK -min 1.001 [get_ports {jtag_vio_DRCK}]
# JTAG Constraints (extra... not used by current Efinity debug tools)
# create_clock -period <USER_PERIOD> [get_ports {jtag_vio_DRCK}]
# set_input_delay -clock_fall -clock jtag_vio_TCK -max 0.864 [get_ports {jtag_vio_RUNTEST}]
# set_input_delay -clock_fall -clock jtag_vio_TCK -min 0.475 [get_ports {jtag_vio_RUNTEST}]
# Create separate clock groups for JTAG clocks. Remove DRCK clock from the list below if it is not defined.
# set_clock_groups -asynchronous -group {jtag_vio_TCK jtag_vio_DRCK}

# 10GBase-KR Constraints
###########################
create_clock -period 5.5652 [get_ports {Q1_L2_10gbe_clk}]
create_clock -period 5.5652 [get_ports {Q3_L2_10gbe_clk}]

set_output_delay -clock Q1_APB_CLK -reference_pin [get_ports {Q1_APB_CLK~CLKOUT~466~244}] -min -0.245 [get_ports {Q1_USER_APB_PADDR[*]}]
set_output_delay -clock Q1_APB_CLK -reference_pin [get_ports {Q1_APB_CLK~CLKOUT~466~244}] -min -0.245 [get_ports {Q1_USER_APB_PSEL}]
set_output_delay -clock Q1_APB_CLK -reference_pin [get_ports {Q1_APB_CLK~CLKOUT~466~244}] -min -0.245 [get_ports {Q1_USER_APB_PENABLE}]
set_output_delay -clock Q1_APB_CLK -reference_pin [get_ports {Q1_APB_CLK~CLKOUT~466~244}] -min -0.245 [get_ports {Q1_USER_APB_PWRITE}]
set_output_delay -clock Q1_APB_CLK -reference_pin [get_ports {Q1_APB_CLK~CLKOUT~466~244}] -min -0.245 [get_ports {Q1_USER_APB_PWDATA[*]}]
set_output_delay -clock Q1_L2_10gbe_clk -reference_pin [get_ports {Q1_L2_10gbe_clk~CLKOUT~465~323}] -min -0.245 [get_ports {Q1_L2_TXD[*]}]
set_output_delay -clock Q1_L2_10gbe_clk -reference_pin [get_ports {Q1_L2_10gbe_clk~CLKOUT~465~323}] -min -0.245 [get_ports {Q1_L2_TXC[*]}]
set_output_delay -clock Q1_L2_10gbe_clk -reference_pin [get_ports {Q1_L2_10gbe_clk~CLKOUT~465~323}] -min -0.245 [get_ports {Q1_L2_PCS_RST_N_TX}]
set_output_delay -clock Q1_L2_10gbe_clk -reference_pin [get_ports {Q1_L2_10gbe_clk~CLKOUT~465~324}] -min -0.245 [get_ports {Q1_L2_PCS_RST_N_RX}]
set_output_delay -clock Q1_APB_CLK -reference_pin [get_ports {Q1_APB_CLK~CLKOUT~466~244}] -max 0.531 [get_ports {Q1_USER_APB_PADDR[*]}]
set_output_delay -clock Q1_APB_CLK -reference_pin [get_ports {Q1_APB_CLK~CLKOUT~466~244}] -max 0.708 [get_ports {Q1_USER_APB_PSEL}]
set_output_delay -clock Q1_APB_CLK -reference_pin [get_ports {Q1_APB_CLK~CLKOUT~466~244}] -max 0.418 [get_ports {Q1_USER_APB_PENABLE}]
set_output_delay -clock Q1_APB_CLK -reference_pin [get_ports {Q1_APB_CLK~CLKOUT~466~244}] -max 0.392 [get_ports {Q1_USER_APB_PWRITE}]
set_output_delay -clock Q1_APB_CLK -reference_pin [get_ports {Q1_APB_CLK~CLKOUT~466~244}] -max 0.543 [get_ports {Q1_USER_APB_PWDATA[*]}]
set_output_delay -clock Q1_L2_10gbe_clk -reference_pin [get_ports {Q1_L2_10gbe_clk~CLKOUT~465~323}] -max 1.019 [get_ports {Q1_L2_TXD[*]}]
set_output_delay -clock Q1_L2_10gbe_clk -reference_pin [get_ports {Q1_L2_10gbe_clk~CLKOUT~465~323}] -max 1.019 [get_ports {Q1_L2_TXC[*]}]
set_output_delay -clock Q1_L2_10gbe_clk -reference_pin [get_ports {Q1_L2_10gbe_clk~CLKOUT~465~323}] -max 1.010 [get_ports {Q1_L2_PCS_RST_N_TX}]
set_output_delay -clock Q1_L2_10gbe_clk -reference_pin [get_ports {Q1_L2_10gbe_clk~CLKOUT~465~324}] -max 0.954 [get_ports {Q1_L2_PCS_RST_N_RX}]
set_input_delay -clock Q1_APB_CLK -reference_pin [get_ports {Q1_APB_CLK~CLKOUT~466~244}] -max 2.152 [get_ports {Q1_USER_APB_PRDATA[*]}]
set_input_delay -clock Q1_APB_CLK -reference_pin [get_ports {Q1_APB_CLK~CLKOUT~466~244}] -min 0.245 [get_ports {Q1_USER_APB_PRDATA[*]}]
set_input_delay -clock Q1_APB_CLK -reference_pin [get_ports {Q1_APB_CLK~CLKOUT~466~244}] -max 1.951 [get_ports {Q1_USER_APB_PREADY}]
set_input_delay -clock Q1_APB_CLK -reference_pin [get_ports {Q1_APB_CLK~CLKOUT~466~244}] -min 0.245 [get_ports {Q1_USER_APB_PREADY}]
set_input_delay -clock Q1_APB_CLK -reference_pin [get_ports {Q1_APB_CLK~CLKOUT~466~244}] -max 2.220 [get_ports {Q1_L2_IRQ}]
set_input_delay -clock Q1_APB_CLK -reference_pin [get_ports {Q1_APB_CLK~CLKOUT~466~244}] -min 0.245 [get_ports {Q1_L2_IRQ}]
set_input_delay -clock Q1_L2_10gbe_clk -reference_pin [get_ports {Q1_L2_10gbe_clk~CLKOUT~465~324}] -max 1.572 [get_ports {Q1_L2_RXD[*]}]
set_input_delay -clock Q1_L2_10gbe_clk -reference_pin [get_ports {Q1_L2_10gbe_clk~CLKOUT~465~324}] -min 0.245 [get_ports {Q1_L2_RXD[*]}]
set_input_delay -clock Q1_L2_10gbe_clk -reference_pin [get_ports {Q1_L2_10gbe_clk~CLKOUT~465~324}] -max 1.572 [get_ports {Q1_L2_RXC[*]}]
set_input_delay -clock Q1_L2_10gbe_clk -reference_pin [get_ports {Q1_L2_10gbe_clk~CLKOUT~465~324}] -min 0.245 [get_ports {Q1_L2_RXC[*]}]
set_input_delay -clock Q1_L2_10gbe_clk -reference_pin [get_ports {Q1_L2_10gbe_clk~CLKOUT~465~324}] -max 1.261 [get_ports {Q1_L2_BLOCK_LOCK}]
set_input_delay -clock Q1_L2_10gbe_clk -reference_pin [get_ports {Q1_L2_10gbe_clk~CLKOUT~465~324}] -min 0.245 [get_ports {Q1_L2_BLOCK_LOCK}]
set_input_delay -clock Q1_L2_10gbe_clk -reference_pin [get_ports {Q1_L2_10gbe_clk~CLKOUT~465~324}] -max 1.280 [get_ports {Q1_L2_HI_BER}]
set_input_delay -clock Q1_L2_10gbe_clk -reference_pin [get_ports {Q1_L2_10gbe_clk~CLKOUT~465~324}] -min 0.245 [get_ports {Q1_L2_HI_BER}]
set_input_delay -clock Q1_L2_10gbe_clk -reference_pin [get_ports {Q1_L2_10gbe_clk~CLKOUT~465~324}] -max 1.340 [get_ports {Q1_L2_PCS_STATUS}]
set_input_delay -clock Q1_L2_10gbe_clk -reference_pin [get_ports {Q1_L2_10gbe_clk~CLKOUT~465~324}] -min 0.245 [get_ports {Q1_L2_PCS_STATUS}]

set_output_delay -clock Q3_APB_CLK -reference_pin [get_ports {Q3_APB_CLK~CLKOUT~466~724}] -min -0.245 [get_ports {Q3_USER_APB_PADDR[*]}]
set_output_delay -clock Q3_APB_CLK -reference_pin [get_ports {Q3_APB_CLK~CLKOUT~466~724}] -min -0.245 [get_ports {Q3_USER_APB_PSEL}]
set_output_delay -clock Q3_APB_CLK -reference_pin [get_ports {Q3_APB_CLK~CLKOUT~466~724}] -min -0.245 [get_ports {Q3_USER_APB_PENABLE}]
set_output_delay -clock Q3_APB_CLK -reference_pin [get_ports {Q3_APB_CLK~CLKOUT~466~724}] -min -0.245 [get_ports {Q3_USER_APB_PWRITE}]
set_output_delay -clock Q3_APB_CLK -reference_pin [get_ports {Q3_APB_CLK~CLKOUT~466~724}] -min -0.245 [get_ports {Q3_USER_APB_PWDATA[*]}]
set_output_delay -clock Q3_L2_10gbe_clk -reference_pin [get_ports {Q3_L2_10gbe_clk~CLKOUT~465~803}] -min -0.245 [get_ports {Q3_L2_TXD[*]}]
set_output_delay -clock Q3_L2_10gbe_clk -reference_pin [get_ports {Q3_L2_10gbe_clk~CLKOUT~465~803}] -min -0.245 [get_ports {Q3_L2_TXC[*]}]
set_output_delay -clock Q3_L2_10gbe_clk -reference_pin [get_ports {Q3_L2_10gbe_clk~CLKOUT~465~803}] -min -0.245 [get_ports {Q3_L2_PCS_RST_N_TX}]
set_output_delay -clock Q3_L2_10gbe_clk -reference_pin [get_ports {Q3_L2_10gbe_clk~CLKOUT~465~804}] -min -0.245 [get_ports {Q3_L2_PCS_RST_N_RX}]
set_output_delay -clock Q3_APB_CLK -reference_pin [get_ports {Q3_APB_CLK~CLKOUT~466~724}] -max 0.531 [get_ports {Q3_USER_APB_PADDR[*]}]
set_output_delay -clock Q3_APB_CLK -reference_pin [get_ports {Q3_APB_CLK~CLKOUT~466~724}] -max 0.708 [get_ports {Q3_USER_APB_PSEL}]
set_output_delay -clock Q3_APB_CLK -reference_pin [get_ports {Q3_APB_CLK~CLKOUT~466~724}] -max 0.418 [get_ports {Q3_USER_APB_PENABLE}]
set_output_delay -clock Q3_APB_CLK -reference_pin [get_ports {Q3_APB_CLK~CLKOUT~466~724}] -max 0.392 [get_ports {Q3_USER_APB_PWRITE}]
set_output_delay -clock Q3_APB_CLK -reference_pin [get_ports {Q3_APB_CLK~CLKOUT~466~724}] -max 0.543 [get_ports {Q3_USER_APB_PWDATA[*]}]
set_output_delay -clock Q3_L2_10gbe_clk -reference_pin [get_ports {Q3_L2_10gbe_clk~CLKOUT~465~803}] -max 1.019 [get_ports {Q3_L2_TXD[*]}]
set_output_delay -clock Q3_L2_10gbe_clk -reference_pin [get_ports {Q3_L2_10gbe_clk~CLKOUT~465~803}] -max 1.019 [get_ports {Q3_L2_TXC[*]}]
set_output_delay -clock Q3_L2_10gbe_clk -reference_pin [get_ports {Q3_L2_10gbe_clk~CLKOUT~465~803}] -max 1.010 [get_ports {Q3_L2_PCS_RST_N_TX}]
set_output_delay -clock Q3_L2_10gbe_clk -reference_pin [get_ports {Q3_L2_10gbe_clk~CLKOUT~465~804}] -max 0.954 [get_ports {Q3_L2_PCS_RST_N_RX}]
set_input_delay -clock Q3_APB_CLK -reference_pin [get_ports {Q3_APB_CLK~CLKOUT~466~724}] -max 2.152 [get_ports {Q3_USER_APB_PRDATA[*]}]
set_input_delay -clock Q3_APB_CLK -reference_pin [get_ports {Q3_APB_CLK~CLKOUT~466~724}] -min 0.245 [get_ports {Q3_USER_APB_PRDATA[*]}]
set_input_delay -clock Q3_APB_CLK -reference_pin [get_ports {Q3_APB_CLK~CLKOUT~466~724}] -max 1.951 [get_ports {Q3_USER_APB_PREADY}]
set_input_delay -clock Q3_APB_CLK -reference_pin [get_ports {Q3_APB_CLK~CLKOUT~466~724}] -min 0.245 [get_ports {Q3_USER_APB_PREADY}]
set_input_delay -clock Q3_APB_CLK -reference_pin [get_ports {Q3_APB_CLK~CLKOUT~466~724}] -max 2.220 [get_ports {Q3_L2_IRQ}]
set_input_delay -clock Q3_APB_CLK -reference_pin [get_ports {Q3_APB_CLK~CLKOUT~466~724}] -min 0.245 [get_ports {Q3_L2_IRQ}]
set_input_delay -clock Q3_L2_10gbe_clk -reference_pin [get_ports {Q3_L2_10gbe_clk~CLKOUT~465~804}] -max 1.572 [get_ports {Q3_L2_RXD[*]}]
set_input_delay -clock Q3_L2_10gbe_clk -reference_pin [get_ports {Q3_L2_10gbe_clk~CLKOUT~465~804}] -min 0.245 [get_ports {Q3_L2_RXD[*]}]
set_input_delay -clock Q3_L2_10gbe_clk -reference_pin [get_ports {Q3_L2_10gbe_clk~CLKOUT~465~804}] -max 1.572 [get_ports {Q3_L2_RXC[*]}]
set_input_delay -clock Q3_L2_10gbe_clk -reference_pin [get_ports {Q3_L2_10gbe_clk~CLKOUT~465~804}] -min 0.245 [get_ports {Q3_L2_RXC[*]}]
set_input_delay -clock Q3_L2_10gbe_clk -reference_pin [get_ports {Q3_L2_10gbe_clk~CLKOUT~465~804}] -max 1.261 [get_ports {Q3_L2_BLOCK_LOCK}]
set_input_delay -clock Q3_L2_10gbe_clk -reference_pin [get_ports {Q3_L2_10gbe_clk~CLKOUT~465~804}] -min 0.245 [get_ports {Q3_L2_BLOCK_LOCK}]
set_input_delay -clock Q3_L2_10gbe_clk -reference_pin [get_ports {Q3_L2_10gbe_clk~CLKOUT~465~804}] -max 1.280 [get_ports {Q3_L2_HI_BER}]
set_input_delay -clock Q3_L2_10gbe_clk -reference_pin [get_ports {Q3_L2_10gbe_clk~CLKOUT~465~804}] -min 0.245 [get_ports {Q3_L2_HI_BER}]
set_input_delay -clock Q3_L2_10gbe_clk -reference_pin [get_ports {Q3_L2_10gbe_clk~CLKOUT~465~804}] -max 1.340 [get_ports {Q3_L2_PCS_STATUS}]
set_input_delay -clock Q3_L2_10gbe_clk -reference_pin [get_ports {Q3_L2_10gbe_clk~CLKOUT~465~804}] -min 0.245 [get_ports {Q3_L2_PCS_STATUS}]

# Clock Latency Constraints
############################
# set_clock_latency -source -setup <board_max + 1.177> [get_ports {DEBUG_CLK}]
# set_clock_latency -source -hold <board_min + 0.785> [get_ports {DEBUG_CLK}]
# set_clock_latency -source -setup <board_max + 1.177> [get_ports {Q1_APB_CLK}]
# set_clock_latency -source -hold <board_min + 0.785> [get_ports {Q1_APB_CLK}]
# set_clock_latency -source -setup <board_max + 1.177> [get_ports {Q3_APB_CLK}]
# set_clock_latency -source -hold <board_min + 0.785> [get_ports {Q3_APB_CLK}]
# set_clock_latency -source -setup <board_max + 1.177> [get_ports {INIT_CLK}]
# set_clock_latency -source -hold <board_min + 0.785> [get_ports {INIT_CLK}]


# Set Async Clock Groups
############################
set_clock_groups -async -group INIT_CLK -group DEBUG_CLK -group Q1_APB_CLK -group Q3_APB_CLK -group Q1_L2_10gbe_clk -group Q3_L2_10gbe_clk -group jtag_vio_TCK
