// =============================================================================
// Generated by efx_ipmgr
// Version: 2025.2.288
// IP Version: 5.0
// =============================================================================

////////////////////////////////////////////////////////////////////////////////
// Copyright (C) 2013-2025 Efinix Inc. All rights reserved.              
//
// This   document  contains  proprietary information  which   is        
// protected by  copyright. All rights  are reserved.  This notice       
// refers to original work by Efinix, Inc. which may be derivitive       
// of other work distributed under license of the authors.  In the       
// case of derivative work, nothing in this notice overrides the         
// original author's license agreement.  Where applicable, the           
// original license agreement is included in it's original               
// unmodified form immediately below this header.                        
//                                                                       
// WARRANTY DISCLAIMER.                                                  
//     THE  DESIGN, CODE, OR INFORMATION ARE PROVIDED “AS IS” AND        
//     EFINIX MAKES NO WARRANTIES, EXPRESS OR IMPLIED WITH               
//     RESPECT THERETO, AND EXPRESSLY DISCLAIMS ANY IMPLIED WARRANTIES,  
//     INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF          
//     MERCHANTABILITY, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR    
//     PURPOSE.  SOME STATES DO NOT ALLOW EXCLUSIONS OF AN IMPLIED       
//     WARRANTY, SO THIS DISCLAIMER MAY NOT APPLY TO LICENSEE.           
//                                                                       
// LIMITATION OF LIABILITY.                                              
//     NOTWITHSTANDING ANYTHING TO THE CONTRARY, EXCEPT FOR BODILY       
//     INJURY, EFINIX SHALL NOT BE LIABLE WITH RESPECT TO ANY SUBJECT    
//     MATTER OF THIS AGREEMENT UNDER TORT, CONTRACT, STRICT LIABILITY   
//     OR ANY OTHER LEGAL OR EQUITABLE THEORY (I) FOR ANY INDIRECT,      
//     SPECIAL, INCIDENTAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES OF ANY    
//     CHARACTER INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF      
//     GOODWILL, DATA OR PROFIT, WORK STOPPAGE, OR COMPUTER FAILURE OR   
//     MALFUNCTION, OR IN ANY EVENT (II) FOR ANY AMOUNT IN EXCESS, IN    
//     THE AGGREGATE, OF THE FEE PAID BY LICENSEE TO EFINIX HEREUNDER    
//     (OR, IF THE FEE HAS BEEN WAIVED, $100), EVEN IF EFINIX SHALL HAVE 
//     BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGES.  SOME STATES DO 
//     NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR            
//     CONSEQUENTIAL DAMAGES, SO THIS LIMITATION AND EXCLUSION MAY NOT   
//     APPLY TO LICENSEE.                                                
//
////////////////////////////////////////////////////////////////////////////////

efx_pcie_dma u_efx_pcie_dma
(
    .axi_clk ( axi_clk ),
    .dma_rstn ( dma_rstn ),
    .apb_clk ( apb_clk ),
    .m_apb_pcie_pready ( m_apb_pcie_pready ),
    .m_apb_pcie_psel ( m_apb_pcie_psel ),
    .m_apb_pcie_pwrite ( m_apb_pcie_pwrite ),
    .m_apb_pcie_penable ( m_apb_pcie_penable ),
    .m_apb_pcie_paddr ( m_apb_pcie_paddr ),
    .m_apb_pcie_pwdata ( m_apb_pcie_pwdata ),
    .m_apb_pcie_pwdata_par ( m_apb_pcie_pwdata_par ),
    .m_apb_pcie_pstrb ( m_apb_pcie_pstrb ),
    .m_apb_pcie_pstrb_par ( m_apb_pcie_pstrb_par ),
    .m_apb_pcie_prdata ( m_apb_pcie_prdata ),
    .m_apb_pcie_prdata_par ( m_apb_pcie_prdata_par ),
    .m_apb_pcie_pslverror ( m_apb_pcie_pslverror ),
    .m_axi_pcie_awaddr ( m_axi_pcie_awaddr ),
    .m_axi_pcie_awid ( m_axi_pcie_awid ),
    .m_axi_pcie_awlen ( m_axi_pcie_awlen ),
    .m_axi_pcie_awsize ( m_axi_pcie_awsize ),
    .m_axi_pcie_awvalid ( m_axi_pcie_awvalid ),
    .m_axi_pcie_awready ( m_axi_pcie_awready ),
    .m_axi_pcie_wlast ( m_axi_pcie_wlast ),
    .m_axi_pcie_wvalid ( m_axi_pcie_wvalid ),
    .m_axi_pcie_wready ( m_axi_pcie_wready ),
    .m_axi_pcie_bresp ( m_axi_pcie_bresp ),
    .m_axi_pcie_bid ( m_axi_pcie_bid ),
    .m_axi_pcie_bvalid ( m_axi_pcie_bvalid ),
    .m_axi_pcie_bready ( m_axi_pcie_bready ),
    .m_axi_pcie_arid ( m_axi_pcie_arid ),
    .m_axi_pcie_araddr ( m_axi_pcie_araddr ),
    .m_axi_pcie_arlen ( m_axi_pcie_arlen ),
    .m_axi_pcie_arsize ( m_axi_pcie_arsize ),
    .m_axi_pcie_arvalid ( m_axi_pcie_arvalid ),
    .m_axi_pcie_arready ( m_axi_pcie_arready ),
    .m_axi_pcie_rid ( m_axi_pcie_rid ),
    .m_axi_pcie_rresp ( m_axi_pcie_rresp ),
    .m_axi_pcie_rlast ( m_axi_pcie_rlast ),
    .m_axi_pcie_rvalid ( m_axi_pcie_rvalid ),
    .m_axi_pcie_rready ( m_axi_pcie_rready ),
    .s_axi_pcie_awid ( s_axi_pcie_awid ),
    .s_axi_pcie_awvalid ( s_axi_pcie_awvalid ),
    .s_axi_pcie_awaddr ( s_axi_pcie_awaddr ),
    .s_axi_pcie_awlen ( s_axi_pcie_awlen ),
    .s_axi_pcie_awsize ( s_axi_pcie_awsize ),
    .s_axi_pcie_awready ( s_axi_pcie_awready ),
    .s_axi_pcie_wvalid ( s_axi_pcie_wvalid ),
    .s_axi_pcie_wdata ( s_axi_pcie_wdata ),
    .s_axi_pcie_wstrb ( s_axi_pcie_wstrb ),
    .s_axi_pcie_wlast ( s_axi_pcie_wlast ),
    .s_axi_pcie_wready ( s_axi_pcie_wready ),
    .s_axi_pcie_bid ( s_axi_pcie_bid ),
    .s_axi_pcie_bresp ( s_axi_pcie_bresp ),
    .s_axi_pcie_bvalid ( s_axi_pcie_bvalid ),
    .s_axi_pcie_bready ( s_axi_pcie_bready ),
    .s_axi_pcie_arid ( s_axi_pcie_arid ),
    .s_axi_pcie_arvalid ( s_axi_pcie_arvalid ),
    .s_axi_pcie_araddr ( s_axi_pcie_araddr ),
    .s_axi_pcie_arlen ( s_axi_pcie_arlen ),
    .s_axi_pcie_arsize ( s_axi_pcie_arsize ),
    .s_axi_pcie_arready ( s_axi_pcie_arready ),
    .s_axi_pcie_rid ( s_axi_pcie_rid ),
    .s_axi_pcie_rvalid ( s_axi_pcie_rvalid ),
    .s_axi_pcie_rdata ( s_axi_pcie_rdata ),
    .s_axi_pcie_rlast ( s_axi_pcie_rlast ),
    .s_axi_pcie_rresp ( s_axi_pcie_rresp ),
    .s_axi_pcie_rready ( s_axi_pcie_rready ),
    .cfg_msi_enable ( cfg_msi_enable ),
    .cfg_msix_enable ( cfg_msix_enable ),
    .legacy_irq ( legacy_irq ),
    .legacy_irq_ack ( legacy_irq_ack ),
    .cfg_max_payload_size ( cfg_max_payload_size ),
    .cfg_max_read_req_size ( cfg_max_read_req_size ),
    .m_apb_usr_penable ( m_apb_usr_penable ),
    .m_apb_usr_paddr ( m_apb_usr_paddr ),
    .m_apb_usr_pwdata ( m_apb_usr_pwdata ),
    .s_apb_usr_prdata ( s_apb_usr_prdata ),
    .s_apb_usr_pready ( s_apb_usr_pready ),
    .s_apb_usr_pslverror ( s_apb_usr_pslverror ),
    .m_axi_pcie_wdata ( m_axi_pcie_wdata ),
    .m_axi_pcie_wdata_par ( m_axi_pcie_wdata_par ),
    .m_axi_pcie_wstrb ( m_axi_pcie_wstrb ),
    .m_axi_pcie_rdata ( m_axi_pcie_rdata ),
    .m_axi_pcie_rdata_par ( m_axi_pcie_rdata_par ),
    .cth_sts ( cth_sts ),
    .htc_sts ( htc_sts ),
    .usr_irq ( usr_irq ),
    .usr_irq_ack ( usr_irq_ack ),
    .apb_rstn ( apb_rstn ),
    .m_apb_usr_pready ( m_apb_usr_pready ),
    .m_apb_usr_prdata ( m_apb_usr_prdata ),
    .m_apb_usr_pslverror ( m_apb_usr_pslverror ),
    .s_apb_usr_paddr ( s_apb_usr_paddr ),
    .s_apb_usr_penable ( s_apb_usr_penable ),
    .s_apb_usr_psel ( s_apb_usr_psel ),
    .s_apb_usr_pwdata ( s_apb_usr_pwdata ),
    .s_apb_usr_pwrite ( s_apb_usr_pwrite ),
    .m_axi_usr_arready ( m_axi_usr_arready ),
    .m_axi_usr_awready ( m_axi_usr_awready ),
    .m_axi_usr_bid ( m_axi_usr_bid ),
    .m_axi_usr_bresp ( m_axi_usr_bresp ),
    .m_axi_usr_bvalid ( m_axi_usr_bvalid ),
    .m_axi_usr_rid ( m_axi_usr_rid ),
    .m_axi_usr_rlast ( m_axi_usr_rlast ),
    .m_axi_usr_rresp ( m_axi_usr_rresp ),
    .m_axi_usr_rvalid ( m_axi_usr_rvalid ),
    .m_axi_usr_wready ( m_axi_usr_wready ),
    .m_axi_usr_rdata ( m_axi_usr_rdata ),
    .m_axi_usr_araddr ( m_axi_usr_araddr ),
    .m_axi_usr_arid ( m_axi_usr_arid ),
    .m_axi_usr_arlen ( m_axi_usr_arlen ),
    .m_axi_usr_arsize ( m_axi_usr_arsize ),
    .m_axi_usr_arvalid ( m_axi_usr_arvalid ),
    .m_axi_usr_awid ( m_axi_usr_awid ),
    .m_axi_usr_awlen ( m_axi_usr_awlen ),
    .m_axi_usr_awsize ( m_axi_usr_awsize ),
    .m_axi_usr_wvalid ( m_axi_usr_wvalid ),
    .m_axi_usr_wlast ( m_axi_usr_wlast ),
    .m_axi_usr_rready ( m_axi_usr_rready ),
    .m_axi_usr_bready ( m_axi_usr_bready ),
    .m_axi_usr_awvalid ( m_axi_usr_awvalid ),
    .m_axi_usr_awaddr ( m_axi_usr_awaddr ),
    .m_axi_usr_wdata ( m_axi_usr_wdata ),
    .m_axi_usr_wstrb ( m_axi_usr_wstrb ),
    .m_apb_usr_psel ( m_apb_usr_psel ),
    .m_apb_usr_pwrite ( m_apb_usr_pwrite )
);
